In [1]:
import dgl
from dgl.data.utils import save_graphs, load_graphs

Using backend: pytorch


In [2]:
import pickle
import numpy as np

In [131]:

graph_path = "/p/reviewde/data/ratebeer/graph/medium_30/graph_batch/"

vocab_file = graph_path+"vocab.pickle"
vocab = None
with open(vocab_file, "rb") as f:
    vocab = pickle.load(f)
vocab_obj = vocab["vocab"]
print("user num", len(vocab_obj.m_user2uid))

user num 1664


In [136]:
graph_path = "/p/reviewde/data/ratebeer/graph/medium_30/graph_batch/train/"

i = 100

g_file_i = graph_path+str(i)+".bin"

g_i, gt_label_i = load_graphs(g_file_i)

In [137]:
g_i = g_i[0]

In [138]:
snode_id = g_i.filter_nodes(lambda nodes: nodes.data["dtype"] == 1)

In [139]:
snode_id

tensor([118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
        132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
        146, 147, 148, 149])

In [140]:
labels = g_i.ndata["label"][snode_id]
labels = labels.view(-1)

In [141]:
raw_sent_id = g_i.ndata["raw_id"][snode_id]

In [142]:
label_num = len(labels)

for i in range(label_num):
    s_i = snode_id[i]
    raw_s_i = raw_sent_id[i]
    label_i = labels[i]
    if label_i.item() == 1:
        print("--"*5)
        s_content_i = vocab_obj.m_sid2swords[raw_s_i.item()]
        print(s_i)
        print(raw_s_i)
        print(s_content_i)
        print(label_i)

----------
tensor(130)
tensor(102881)
good hoppy aroma nice dark reddish pour .
tensor(1)
----------
tensor(137)
tensor(102882)
good hops taste a bit bitter but very tasty i like this one and woudl buy again
tensor(1)


In [143]:
labels

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0])

In [144]:
labels.size()

torch.Size([32])

In [145]:
for i in labels:
    if i.item() == 1:
        print(i)

tensor(1)
tensor(1)


In [146]:
raw_sent_id = g_i.ndata["raw_id"][snode_id]

In [147]:
raw_sent_id

tensor([463441, 102766,  29608,  32219, 102748, 117868, 429146,  38190, 431311,
        463663, 102929, 408434, 102881, 407937, 102639,  25309, 333113, 116233,
        481006, 102882, 131342, 180362,  85643, 481005, 104355, 298031, 308598,
        102893, 274285, 102702, 480291, 290330])

In [148]:
for sid_k in raw_sent_id:
    
    
    print(vocab_obj.m_sid2swords[sid_k.item()])

mouthfeel is medium with some prickly feeling and a nice , crisp finish .
an unremarkable beer at best .
a sticky brew and i loved it .
i love me a good ol fashioned hop whompin and furious delivers .
i would nt buy again but do nt mind that i have 5 more to drink
i was surprised that this was an ipa and not a double .
kind of like the abrasive that i had earlier in the day , it was a good mixture of dark ( chocolate , caramel , malty ) and citrus ( pine , grapefruit ) .
pours murky brown with foamy beige head .
flavor is grapefruit hops with a nice malty finish to balance the beer .
the taste is bitter but with a little sweetness that is also there .
the best part of this beer is the blonde on the bottle .
looks like a long - aged bourbon in the glass .
good hoppy aroma nice dark reddish pour .
my my my ... a top 5 beer i say myself .
a good balance of hops and malt .
the citrus - juiced hops follow through into the flavor , yet there s a danish - like malt center that give startling 

In [149]:
unode_id_j = g_i.filter_nodes(lambda nodes: nodes.data["dtype"]==2)
uid_j = g_i.nodes[unode_id_j].data["raw_id"]

inode_id_j = g_i.filter_nodes(lambda nodes: nodes.data["dtype"]==3)
iid_j = g_i.nodes[inode_id_j].data["raw_id"]

In [150]:
print("==="*10)
print("user id", uid_j.item())
print("item id", iid_j.item())

user id 0
item id 700


In [151]:
user2uid = vocab_obj.m_user2uid
item2iid = vocab_obj.m_item2iid


In [152]:
uid2user = {}
iid2item = {}

for user in user2uid:
    uid2user[user2uid[user]] = user

for item in item2iid:
    iid2item[item2iid[item]] = item


In [153]:
uid2user[uid_j.item()], iid2item[iid_j.item()]

('1000', '227')

In [154]:
label_sid_list_j = gt_label_i["gt_label"]
refs_j = []
for sid_k in label_sid_list_j:
    refs_j.append(vocab_obj.m_sid2swords[sid_k.item()])

In [155]:
# hyps_j = " ".join(hyps_j)
refs_j = " ".join(refs_j)

# print("hyps_j", hyps_j)
print("refs_j", refs_j)

refs_j good hops taste a bit bitter but very tasty i like this one and woudl buy again good hoppy aroma nice dark reddish pour .


In [158]:
def sigmoid(x):
    return 1.0/(1.0+np.exp(-x))

In [161]:
x = 0.3313
print(sigmoid(x))

0.5820756532067559


In [31]:
graph_path = "/p/reviewde/data/ratebeer/graph/small_500_v2/graph_batch/valid/"

i = 10

g_file_i = graph_path+str(i)+".bin"

g_i, label_i = load_graphs(g_file_i)

g_i = g_i[0]

In [32]:
snode_id = g_i.filter_nodes(lambda nodes: nodes.data["dtype"] == 1)
labels = g_i.ndata["label"][snode_id]
labels = labels.view(-1)

In [33]:
for i in labels:
    if i.item() == 1:
        print(i)

In [34]:
print(labels.size())

torch.Size([291])


In [35]:
labels

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0])

### check item clustering

In [19]:
data_dir = "/p/reviewde/data/ratebeer/graph/small_30/"
item_feature_file = data_dir+"train/item/item2feature.json"

In [24]:
def readJson(fname):
    data = []
    line_num = 0
    with open(fname, encoding="utf-8") as f:
        for line in f:
#             print("line", line)
            try:
                data.append(json.loads(line))
            except:
                print("error", line_num)
    return data

In [25]:
iid2fid2tfidf_dict = {}

itemid2fid2tfidf = readJson(item_feature_file)[0]
item_num = len(itemid2fid2tfidf)
print("item_num", item_num)
   

1
error 1


IndexError: list index out of range